name: Markdown file check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js 16
          uses: actions/setup-node@v2
          with:
            node-version: 16
            cache: 'npm'
        - name: Install Dependencies
          run: npm ci
        - name: Test Frontmatter Content
          run: npm run test:frontmatter