# This workflow will test the content present in markdown files and check for any corrupt index

name: Build + Test Gatsby Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test Frontmatter Content
    runs-on: ubuntu-latest

    steps:
    - name: Test Frontmatter Content
      run: npm run test:frontmatter
